name: Deploy website
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Fetches code from the git repo with the commit hash that triggered the action
      - name: Get code
        uses: actions/checkout@v3
      # caching dependencies for npm packages
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # creates a new hash key if lock file is updated
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        # Get cached dependencies if it exists
      - name: Get Cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Check build files
        run: echo "ls"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files-artifact-name
          path: build
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name : Get build artifacts
        uses : actions/download-artifact@v3
        with :
            name: build-files-artifact-name
      - name: Output contents of the downloaded artifacts
        run: |
          echo "${{ toJSON(github) }}"
          echo "Displaying list of downloaded artifacts..."
          ls

